spring:
  application:
    name: music-library
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cjp
    url: jdbc:mysql://localhost:3306/music_lib?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  data:
    redis:
      host: 192.168.0.105
      port: 6379
server:
  port: 9090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.cjp.musiclibrary.domain


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cjp.musiclibrary.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn